name: Tests

on: [push, pull_request]


jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
          # clone in the gopath
          path: src/github.com/${{ github.repository }}
      - uses: actions/setup-go@v6
        with:
          #go-version-file: 'go.mod'
          go-version: '1.25'
          check-latest: true
      - run: |
          echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - run: |
          cd $GITHUB_WORKSPACE/src/github.com/${{ github.repository }}
          go build
          exit_code=0
          ./lol -h || exit_code=$?
          if [ "${exit_code}" -eq 2 ]
          then
            exit 0
          fi
          exit $exit_code
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2
          # clone in the gopath
          path: src/github.com/${{ github.repository }}
      - uses: actions/setup-go@v6
        with:
          #go-version-file: 'go.mod'
          go-version: '1.25'
          check-latest: true
      - run: |
          echo "GOPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - run: |
          cd $GITHUB_WORKSPACE/src/github.com/${{ github.repository }}
          go get -v -t ./...
          echo "" > coverage.txt
          for d in $(go list ./...); do
              go test -v -race -coverprofile=profile.out -covermode=atomic "${d}"
              if [ -f profile.out ]; then
                cat profile.out >> coverage.txt
                rm profile.out
              fi
          done
          bash <(curl -s https://codecov.io/bash) -c -f coverage.txt -F unittest
